version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/node-red-contrib-debug-file
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
