 'use strict';
// All registry checks fail closed. Never interpret a network/auth error as availability.
const assert = require('node:assert/strict');
const cp = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const run = (cmd,args) => cp.execFileSync(cmd,args,{encoding:'utf8'}).trim();
const api = route => JSON.parse(run('gh',['api',route]));
(async () => {
  const tag = process.env.RELEASE_TAG;
  const repo = process.env.GITHUB_REPOSITORY;
  const selected = require('./package.cjs')();
  assert(tag && tag.startsWith(`${selected.name}/v`));
  assert.match(tag.slice(selected.name.length + 1), /^v\d+\.\d+\.\d+$/);
  assert(process.env.EXPECTED_NPM_OWNER, 'NPM_OWNER must be verified and configured');
  const environment = api(`repos/${repo}/environments/${selected.environment}`);
  assert(environment.protection_rules.some(r => r.type === 'required_reviewers' && r.reviewers.length), 'Required environment reviewer missing');
  assert(environment.deployment_branch_policy?.custom_branch_policies, 'Environment tag restrictions missing');
  const policies = api(`repos/${repo}/environments/${selected.environment}/deployment-branch-policies`).branch_policies;
  assert(policies.length === 1 && policies[0].name === `${selected.name}/v*` && policies[0].type === 'tag', 'Environment must allow only v* tags');
  const protection = api(`repos/${repo}/branches/main/protection`);
  assert(protection.enforce_admins.enabled && protection.required_pull_request_reviews.required_approving_review_count >= 1, 'Protected main and PR approvals required');
  assert(protection.required_status_checks.strict && ['test (node-red-contrib-debug-file, 22)','test (node-red-contrib-debug-file, 24)','audit','workflow-and-secrets','codeql','dependency-review'].every(name => protection.required_status_checks.checks.some(check => check.context === name && check.app_id === 15368)), 'Required security checks missing');
  const rules = api(`repos/${repo}/rulesets`);
  const details = rules.filter(r => r.target === 'tag' && r.enforcement === 'active').map(r => api(`repos/${repo}/rulesets/${r.id}`));
  assert(details.some(r => (r.conditions.ref_name.include.includes(`refs/tags/${selected.name}/v*`) || r.conditions.ref_name.include.includes('refs/tags/*/v*')) && ['update','deletion'].every(type => r.rules.some(rule => rule.type === type)) && (!r.bypass_actors || !r.bypass_actors.length)), 'Immutable v* tag ruleset required without bypass actors');
  const release = api(`repos/${repo}/releases/tags/${encodeURIComponent(tag)}`);
  assert(!release.draft && !release.prerelease && release.tag_name === tag);
  const remoteTag = run('git', ['ls-remote', '--tags', 'origin', `refs/tags/${tag}`]).split('\t')[0];
  assert.equal(remoteTag, run('git', ['rev-parse', tag]), 'Remote tag changed');
  const sha = run('git',['rev-parse',`${tag}^{commit}`]);
  assert.equal(process.env.GITHUB_REF, `refs/tags/${tag}`, 'Dispatch from the release tag for correct provenance');
  assert.equal(process.env.GITHUB_SHA, sha, 'Workflow identity must match release commit');
  run('git',['merge-base','--is-ancestor',sha,'origin/main']);
  run('git',['checkout','--detach',sha]);
  process.chdir(selected.directory);
  const pkg = JSON.parse(fs.readFileSync('package.json'));
  assert.equal(tag, `${selected.name}/v${pkg.version}`);
  assert.equal(process.env.CONFIRM_PACKAGE, pkg.name);
  assert.equal(pkg.repository && pkg.repository.url, `git+https://github.com/${repo}.git`, 'Repository metadata is required for provenance; use a new version, never rewrite a released tag');
  for (const key of ['prepublish','prepublishOnly','prepare','prepack','postpack','publish','postpublish']) assert(!pkg.scripts?.[key], 'Publishing lifecycle scripts forbidden');
  const response = await fetch(`https://registry.npmjs.org/${encodeURIComponent(pkg.name)}`, {signal: AbortSignal.timeout(15000)});
  assert.equal(response.status, 200, 'First publication requires separate verified bootstrap authorization');
  const metadata = await response.json();
  assert(metadata.maintainers.some(m => m.name === process.env.EXPECTED_NPM_OWNER), 'Verified npm owner absent');
  assert(!metadata.versions[pkg.version], 'Version already published; do not retry or overwrite');
  const filename = `${pkg.name.replace('@', '').replace('/', '-')}-${pkg.version}.tgz`;
  assert.equal(release.assets.filter(a => a.name === filename).length, 1, 'One exact release archive required');
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'npm-release-'));
  run('gh', ['release', 'download', tag, '--repo', repo, '--pattern', filename, '--dir', dir]);
  fs.appendFileSync(process.env.GITHUB_ENV, `RELEASE_ARCHIVE=${path.join(dir, filename)}\n`);
  console.log(`Verified ${pkg.name}@${pkg.version} at ${sha}`);
})().catch(() => { console.error('Publishing preflight failed; review ownership, release metadata and repository protections. No publication attempted.'); process.exitCode = 1; });
